project_id: 12
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true
base_url: "https://hacks-guide.api.crowdin.com"

files:
  - source: /docs/*.md
    translation: /docs/%locale_with_underscore%/%original_file_name%
  - source: /docs/.vitepress/i18n/strings/en_US.json
    translation: /docs/.vitepress/i18n/strings/%locale_with_underscore%.json
